# Introduction

Most drivers in America are familiar with the situation of getting pulled over while on the road. The reasons can be anything from speeding to a having a broken tail light, which are obvious examples of law-breaking. More serious grounds could be if the driver possessed any contraband items. The results of these traffic stops may range to a simple warning to a ticket or citation. One might wonder if there there is any patterns to how police survey the population looking for illegal activity on the road. Indeed, there has been much research already done on this front, such as an article by the New York Times "Confronting Implicit Bias in the New York Police Department." There have been countless articles such as this one detailing the unconscious racial biases present in police departments towards minorities and especially Blacks. However, this story is not simply limited to race. For this project, we wish to uncover a larger story of police stops using a variety of features outside of only demographics. 

We will use data from policing records provided by the Stanford Computational Journalism Lab, the Knight Foundation, and the Stanford Computational Policy Lab. There is data collected from almost one hundred major cities around the United States, but we chose to focus on the records from Nashville, Tennessee. 

We are interested in how different features of the traffic stop are related to one another, including its temporal aspect, its geographic location, and the demographic data of the driver. It may be interesting to see if more people are stopped during a certain time of day (such as rush hour) or at a busy location (such as a large intersection). Maybe there is a distinction between the brand of car driven or the age of the vehicle and if the driver will be pulled over. Additionally, there are certain stereotypes about race and driving that may also be evident. Are Asians really the worst drivers? Are male drivers more reckless? These are among the questions that we plan to investigate through exploration of our data.
